spring:
  application:
    name: web-security-scanner-cli
  
  # Disable web server for CLI mode
  main:
    web-application-type: none
  
  # Disable database for CLI mode
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Enable CLI functionality
scanner:
  cli:
    enabled: true

logging:
  level:
    io.github.burakkaygusuz: INFO
    org.springframework: WARN
    org.hibernate: OFF
