# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Web Security Scanner CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=2

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: ['21']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Validate Maven configuration
        run: mvn validate
      
      - name: Compile project
        run: mvn -B compile --fail-at-end
      
      - name: Check code formatting
        run: mvn -B com.spotify.fmt:fmt-maven-plugin:check
      
      - name: Run tests with test profile
        run: mvn -B test -Dspring.profiles.active=test
        env:
          MAVEN_OPTS: -Xmx1024m
      
      - name: Generate test report
        run: mvn -B surefire-report:report-only
        if: always()
      
      - name: Build JAR package
        run: mvn -B package -DskipTests
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-java-${{ matrix.java }}
          path: |
            target/surefire-reports/
            target/site/surefire-report.html
          retention-days: 30
      
      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts-java-${{ matrix.java }}
          path: |
            target/*.jar
            !target/*-sources.jar
            !target/*-javadoc.jar
          retention-days: 30
      
      - name: Test Summary
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results (Java ${{ matrix.java }})
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Run code quality checks
        run: |
          mvn -B compile
          mvn -B com.spotify.fmt:fmt-maven-plugin:check
          echo "✅ Code quality checks passed"
